### PR TITLE
Add separate bin/ci.sh script with strict error handling.

### PR DESCRIPTION
**Pull request by iamazeem**
Add separate `bin/ci.sh` script with strict error handling.

Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

### CODE REVIEW

**Comment by OriHoch** [comment]
is this related to an issue?

**Comment by OriHoch** [comment]
oh, I see it's meant to help fix CloudWebManage/cwm-worker-cluster#74

**Comment by iamazeem** [comment]
@OriHoch 
We need to update other CI scripts as well at some point in the future to avoid cases where CI fails silently.
Though the other scripts are working fine so far.
Combing the script commands with `&&\` creates blindspots for debugging where no logging to stdout/stderr is provided.
What's your take on it?

**Comment by OriHoch** [comment]
when we encounter such a blidspot we can fix it, no point to fix it now

**Pull request merged**
